using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Runs;
using TheArchitectCup.Content;
using TheArchitectCup.Features.CardGeneration;
using TheArchitectCup.Settings;

namespace TheArchitectCup.Api;

/// <summary>Supported integration surface for The Architect Cup.</summary>
public static class ArchitectCupApi
{
    /// <summary>Current public API contract version.</summary>
    public const int ApiVersion = 1;

    /// <summary>Stable metadata for every card provided by the mod.</summary>
    public static IReadOnlyList<ArchitectCupCardInfo> Cards { get; } =
        ArchitectCupCardCatalog.All.Select(static definition => definition.ToPublicInfo()).ToArray();

    /// <summary>Returns whether a configurable card is enabled locally or in the supplied run.</summary>
    public static bool IsCardEnabled(string cardId, RunState? runState = null) =>
        runState == null
            ? CardSettingsService.IsCardEnabled(cardId)
            : CardSettingsService.IsCardEnabled(cardId, runState);

    /// <summary>
    /// Registers a deterministic predicate for cards generated by Burn the Mountain.
    /// Every multiplayer peer must register the same predicate under the same ID.
    /// </summary>
    public static IDisposable RegisterCrossCharacterCardFilter(
        string registrationId,
        Func<CrossCharacterCardFilterContext, CardModel, bool> filter) =>
        CrossCharacterCardFilterRegistry.Register(registrationId, filter);
}
